logging:
  level:
    com.csy.cloud.openfeign.serivce: debug


  spring:
    cloud:
      openfeign:
        client:
          config:
            default: # 全局默认配置
              connectTimeout: 5000 # 连接超时 (毫秒)
              readTimeout: 5000    # 读取超时 (毫秒) - 生产建议 3-5秒
            nacos-provider: # 针对特定服务的特殊配置
              readTimeout: 10000   # 这个服务比较慢，给它 10秒

