server:
  port: 9001
  servlet:
    context-path: /nacos-provider

spring:
  application:
    name: nacos-provider # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 地址
        # --- 1. 账号密码配置 ---
        # 如果你的 Nacos 开启了鉴权（nacos.core.auth.enabled=true），必须配置这两项
        username: nacos  # 这里填你的 Nacos 账号，默认通常是 nacos
        password: nacos  # 这里填你的 Nacos 密码，默认通常是 nacos

        # --- 2. 命名空间 (Namespace) 配置 ---
        # 作用：用于隔离不同的部署环境（如开发环境 dev、测试环境 test、生产环境 prod）
        # 坑点预警：这里填的必须是 Nacos 控制台生成的【命名空间 ID】，而不是名称！
        # 假设我们在控制台新建了一个命名空间，ID 为 "csy-cloud-dev"
        namespace: d4a9513f-cd2f-4d1d-95c9-1bb5c273eab2

        # --- 3. 分组 (Group) 配置 ---
        # 作用：用于隔离不同的业务项目（如商城项目组、物流项目组）
        # 默认是 DEFAULT_GROUP。这里我们定义为 "LEARNING_GROUP" (学习项目组)
        group: LEARNING_GROUP
