server:
  port: 8001
spring:
  application:
    name: service-order # 微服务名称，未来 Nacos 注册就用这个名字
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 日志，方便调试
    map-underscore-to-camel-case: true # 开启下划线转驼峰 (order_no -> orderNo)